inherit_from: .rubocop_todo.yml

#### The following group of customizations is questionable. ####

AllCops:
  TargetRubyVersion: 1.9
  Exclude:
    - 'spec/**/*'
    - 'benchmarking/**/*'
    - 'support/**/*'
    - 'integration/**/*'
    - 'features/**/*'
    - 'tmp/**/*'

# We shouldn't rescue Exception!
Lint/RescueException:
  Exclude:
    - 'lib/cassandra/executors.rb'

#### Good customizations ####
Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Style/MultilineBlockLayout:
  Enabled: false

Style/MultilineTernaryOperator:
  Enabled: false

Style/PredicateName:
  NamePrefixBlacklist: is_, have_
  NameWhitelist: is_a?

Style/SingleLineBlockParams:
  Enabled: false

Style/SignalException:
  EnforcedStyle: only_raise

Style/TrivialAccessors:
  Enabled: false

Lint/EndAlignment:
  AutoCorrect: true

Style/IfUnlessModifier:
  MaxLineLength: 120

Style/RaiseArgs:
  Enabled: false

Style/WhileUntilModifier:
  MaxLineLength: 120

Metrics/LineLength:
  Max: 120
  # To make it possible to copy or click on URIs in the code, we allow lines
  # contaning a URI to be longer than Max.
  AllowHeredoc: true
  AllowURI: true
  URISchemes:
    - http
    - https

# Offense count: 78
# Cop supports --auto-correct.
# Configuration parameters: AllowUnusedKeywordArguments, IgnoreEmptyMethods.
Lint/UnusedMethodArgument:
  Enabled: false

# Offense count: 3
# Cop supports --auto-correct.
Style/MutableConstant:
  Exclude:
    - 'lib/cassandra/protocol/response.rb'
    - 'lib/cassandra/protocol/responses/event_response.rb'
    - 'lib/cassandra/protocol/responses/result_response.rb'

