schedules:
  commit:
    schedule: per_commit
    enable_pull_requests: true
    matrix:
      exclude:
        - ruby: ['2.2']
        - cassandra: ['2.2', '3.0']
  nightly:
    schedule: nightly
    branches:
      include: [master]

ruby:
  - 2.2
  - 2.3
  - 2.4
  - jruby9k

cassandra:
  - '2.1'
  - '3.0'
  - '3.11'
  - '4.0'
os:
  - ubuntu/bionic64/ruby-driver
build:
  - script: |
      ruby_version=`ruby --version`
      if [[ `ruby --version` == jruby* ]]; then
        # Add '-java' to version as that is included in version name when using jruby
        sed -i -r 's/cassandra-driver \((.*)\)/cassandra-driver (\1-java)/' Gemfile.lock
      fi
  - type: bundler
    without: development docs
  - script: |
      # Set the Java paths (for CCM)
      export JAVA_HOME=$CCM_JAVA_HOME
      export PATH=$JAVA_HOME/bin:$PATH

      # Define Cassandra or DSE runtime
      if [ "$CCM_IS_DSE" == "true" ]; then
        export DSE_VERSION=$CCM_VERSION
      else
        export CASSANDRA_VERSION=$CCM_VERSION
      fi

      # Run the tests
      bundle exec rake test
