schedules:
  commit:
    schedule: per_commit
    matrix:
      exclude:
        - ruby: ['2.2', 'jruby1.7']
        - cassandra: ['2.2', '3.0']
  nightly:
    schedule: nightly
    branches:
      include: [master]

ruby:
  - 2.2
  - 2.3
  - 2.4
  - jruby1.7
  - jruby9k
cassandra:
  - 2.1
  - 2.2
  - 3.0
  - '3.10'
os:
  - ubuntu/trusty64
build:
  - type: bundler
    without: development docs
  - script: |
      # Set the Java paths (for CCM)
      export JAVA_HOME=$CCM_JAVA_HOME
      export PATH=$JAVA_HOME/bin:$PATH

      # Define Cassandra or DSE runtime
      if [ "$CCM_IS_DSE" == "true" ]; then
        export DSE_VERSION=$CCM_VERSION
      else
        export CASSANDRA_VERSION=$CCM_VERSION
      fi

      # Run the tests
      bundle exec rake test
