schedules:
  commit:
    schedule: per_commit
    matrix:
      exclude:
        - ruby: ['2.2', 'jruby1.7']
        - cassandra: ['2.2', '3.0']
  nightly:
    schedule: nightly
    branches:
      include: [master]

ruby:
  - 2.2
  - 2.3
  - jruby1.7
  - jruby9k
cassandra:
  - 2.1
  - 2.2
  - 3.0
  - '3.10'
os:
  - ubuntu/trusty64
build:
  - type: bundler
    without: development docs
  - script: |
      # Set the Java paths (for CCM)
      export JAVA_HOME=$CCM_JAVA_HOME
      export PATH=$JAVA_HOME/bin:$PATH

      # Define Cassandra or DSE runtime
      if [ "$CCM_IS_DSE" == "true" ]; then
        export DSE_VERSION=$CCM_VERSION
      else
        export CASSANDRA_VERSION=$CCM_VERSION
      fi

      # Run the tests; `bundle exec rake test` does all this but seems to be unstable
      # in JRuby9k, so we break down the phases ourselves.
      RC=0
      bundle exec rake compile
      if [ $? -eq 0 ] ; then
        echo "About to launch unit tests"
        bundle exec rake rspec
        if [ $? -eq 0 ] ; then
          echo "Unit tests completed successfully"
          bundle exec rake integration
          if [ $? -eq 0 ] ; then
            echo "Integration tests completed successfully"
            bundle exec rake cucumber
            if [ $? -eq 0 ] ; then
              echo "Features ran successfully"
            else
              echo "Features failed"
              RC=1
            fi
          else
            echo "Integration tests failed"
            RC=1
          fi
        else
          echo "Unit tests failed"
          RC=1
        fi
      else
        echo "Compile failed"
        RC=1
      fi
      if [ $RC -ne 0 ] ; then
        bin/false
      fi
