# encoding: utf-8

#--
# Copyright 2013-2014 DataStax, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#++

require 'spec_helper'

module Cassandra
  class Cluster
    describe(Schema) do
      subject { Schema.new(Cluster::Schema::TypeParser.new) }

      describe('#update_keyspaces') do
        context 'with cassandra 2.0' do
          let(:host)      { Cassandra::Host.new('127.0.0.1', nil, nil, nil, '2.0.10') }
          let(:keyspaces) {
            [
              {
                'keyspace_name'    => 'system',
                'durable_writes'   => true,
                'strategy_class'   => 'org.apache.cassandra.locator.LocalStrategy',
                'strategy_options' => '{}'
              },
              {
                'keyspace_name'    => 'system_traces',
                'durable_writes'   => true,
                'strategy_class'   => 'org.apache.cassandra.locator.SimpleStrategy',
                "strategy_options" => "{\"replication_factor\":\"2\"}"
              },
              {
                'keyspace_name'    => 'simplex',
                'durable_writes'   => true,
                'strategy_class'   => 'org.apache.cassandra.locator.SimpleStrategy',
                "strategy_options" => "{\"replication_factor\":\"3\"}"
              },
            ]
          }
          let(:tables) {
            [
              {
                "keyspace_name"=>"system",
                "columnfamily_name"=>"IndexInfo",
                "bloom_filter_fp_chance"=>"0.01",
                "caching"=>"KEYS_ONLY",
                "column_aliases"=>"[\"index_name\"]",
                "comment"=>"indexes that have been completed",
                "compaction_strategy_class"=>
                 "org.apache.cassandra.db.compaction.SizeTieredCompactionStrategy",
                "compaction_strategy_options"=>"{}",
                "comparator"=>"org.apache.cassandra.db.marshal.UTF8Type",
                "compression_parameters"=>
                 "{\"sstable_compression\":\"org.apache.cassandra.io.compress.LZ4Compressor\"}",
                "default_time_to_live"=>"0",
                "default_validator"=>"org.apache.cassandra.db.marshal.BytesType",
                "dropped_columns"=>nil,
                "gc_grace_seconds"=>"0",
                "index_interval"=>"128",
                "is_dense"=>"true",
                "key_aliases"=>"[\"table_name\"]",
                "key_validator"=>"org.apache.cassandra.db.marshal.UTF8Type",
                "local_read_repair_chance"=>"0.0",
                "max_compaction_threshold"=>"32",
                "memtable_flush_period_in_ms"=>"3600000",
                "min_compaction_threshold"=>"4",
                "populate_io_cache_on_flush"=>"false",
                "read_repair_chance"=>"0.0",
                "replicate_on_write"=>"true",
                "speculative_retry"=>"99.0PERCENTILE",
                "subcomparator"=>nil,
                "type"=>"Standard",
                "value_alias"=>""
              },
              {
                "keyspace_name"=>"system",
                "columnfamily_name"=>"NodeIdInfo",
                "bloom_filter_fp_chance"=>"0.01",
                "caching"=>"KEYS_ONLY",
                "column_aliases"=>"[\"id\"]",
                "comment"=>"counter node IDs",
                "compaction_strategy_class"=>
                 "org.apache.cassandra.db.compaction.SizeTieredCompactionStrategy",
                "compaction_strategy_options"=>"{}",
                "comparator"=>"org.apache.cassandra.db.marshal.TimeUUIDType",
                "compression_parameters"=>
                 "{\"sstable_compression\":\"org.apache.cassandra.io.compress.LZ4Compressor\"}",
                "default_time_to_live"=>"0",
                "default_validator"=>"org.apache.cassandra.db.marshal.BytesType",
                "dropped_columns"=>nil,
                "gc_grace_seconds"=>"0",
                "index_interval"=>"128",
                "is_dense"=>"true",
                "key_aliases"=>"[\"key\"]",
                "key_validator"=>"org.apache.cassandra.db.marshal.UTF8Type",
                "local_read_repair_chance"=>"0.0",
                "max_compaction_threshold"=>"32",
                "memtable_flush_period_in_ms"=>"3600000",
                "min_compaction_threshold"=>"4",
                "populate_io_cache_on_flush"=>"false",
                "read_repair_chance"=>"0.0",
                "replicate_on_write"=>"true",
                "speculative_retry"=>"99.0PERCENTILE",
                "subcomparator"=>nil,
                "type"=>"Standard",
                "value_alias"=>""
              },
              {
                "keyspace_name"=>"system",
                "columnfamily_name"=>"batchlog",
                "bloom_filter_fp_chance"=>"0.01",
                "caching"=>"KEYS_ONLY",
                "column_aliases"=>"[]",
                "comment"=>"uncommited batches",
                "compaction_strategy_class"=>
                 "org.apache.cassandra.db.compaction.SizeTieredCompactionStrategy",
                "compaction_strategy_options"=>"{\"min_threshold\":\"2\"}",
                "comparator"=>
                 "org.apache.cassandra.db.marshal.CompositeType(org.apache.cassandra.db.marshal.UTF8Type)",
                "compression_parameters"=>
                 "{\"sstable_compression\":\"org.apache.cassandra.io.compress.LZ4Compressor\"}",
                "default_time_to_live"=>"0",
                "default_validator"=>"org.apache.cassandra.db.marshal.BytesType",
                "dropped_columns"=>nil,
                "gc_grace_seconds"=>"0",
                "index_interval"=>"128",
                "is_dense"=>"false",
                "key_aliases"=>"[\"id\"]",
                "key_validator"=>"org.apache.cassandra.db.marshal.UUIDType",
                "local_read_repair_chance"=>"0.0",
                "max_compaction_threshold"=>"32",
                "memtable_flush_period_in_ms"=>"3600000",
                "min_compaction_threshold"=>"2",
                "populate_io_cache_on_flush"=>"false",
                "read_repair_chance"=>"0.0",
                "replicate_on_write"=>"true",
                "speculative_retry"=>"99.0PERCENTILE",
                "subcomparator"=>nil,
                "type"=>"Standard",
                "value_alias"=>nil
              },
              {
                "keyspace_name"=>"system",
                "columnfamily_name"=>"compaction_history",
                "bloom_filter_fp_chance"=>"0.01",
                "caching"=>"KEYS_ONLY",
                "column_aliases"=>"[]",
                "comment"=>"show all compaction history",
                "compaction_strategy_class"=>
                 "org.apache.cassandra.db.compaction.SizeTieredCompactionStrategy",
                "compaction_strategy_options"=>"{}",
                "comparator"=>
                 "org.apache.cassandra.db.marshal.CompositeType(org.apache.cassandra.db.marshal.UTF8Type,org.apache.cassandra.db.marshal.ColumnToCollectionType(726f77735f6d6572676564:org.apache.cassandra.db.marshal.MapType(org.apache.cassandra.db.marshal.Int32Type,org.apache.cassandra.db.marshal.LongType)))",
                "compression_parameters"=>
                 "{\"sstable_compression\":\"org.apache.cassandra.io.compress.LZ4Compressor\"}",
                "default_time_to_live"=>"604800",
                "default_validator"=>"org.apache.cassandra.db.marshal.BytesType",
                "dropped_columns"=>nil,
                "gc_grace_seconds"=>"0",
                "index_interval"=>"128",
                "is_dense"=>"false",
                "key_aliases"=>"[\"id\"]",
                "key_validator"=>"org.apache.cassandra.db.marshal.UUIDType",
                "local_read_repair_chance"=>"0.0",
                "max_compaction_threshold"=>"32",
                "memtable_flush_period_in_ms"=>"3600000",
                "min_compaction_threshold"=>"4",
                "populate_io_cache_on_flush"=>"false",
                "read_repair_chance"=>"0.0",
                "replicate_on_write"=>"true",
                "speculative_retry"=>"99.0PERCENTILE",
                "subcomparator"=>nil,
                "type"=>"Standard",
                "value_alias"=>nil
              },
              {
                "keyspace_name"=>"system",
                "columnfamily_name"=>"compactions_in_progress",
                "bloom_filter_fp_chance"=>"0.01",
                "caching"=>"KEYS_ONLY",
                "column_aliases"=>"[]",
                "comment"=>"unfinished compactions",
                "compaction_strategy_class"=>
                 "org.apache.cassandra.db.compaction.SizeTieredCompactionStrategy",
                "compaction_strategy_options"=>"{}",
                "comparator"=>
                 "org.apache.cassandra.db.marshal.CompositeType(org.apache.cassandra.db.marshal.UTF8Type,org.apache.cassandra.db.marshal.ColumnToCollectionType(696e70757473:org.apache.cassandra.db.marshal.SetType(org.apache.cassandra.db.marshal.Int32Type)))",
                "compression_parameters"=>
                 "{\"sstable_compression\":\"org.apache.cassandra.io.compress.LZ4Compressor\"}",
                "default_time_to_live"=>"0",
                "default_validator"=>"org.apache.cassandra.db.marshal.BytesType",
                "dropped_columns"=>nil,
                "gc_grace_seconds"=>"0",
                "index_interval"=>"128",
                "is_dense"=>"false",
                "key_aliases"=>"[\"id\"]",
                "key_validator"=>"org.apache.cassandra.db.marshal.UUIDType",
                "local_read_repair_chance"=>"0.0",
                "max_compaction_threshold"=>"32",
                "memtable_flush_period_in_ms"=>"3600000",
                "min_compaction_threshold"=>"4",
                "populate_io_cache_on_flush"=>"false",
                "read_repair_chance"=>"0.0",
                "replicate_on_write"=>"true",
                "speculative_retry"=>"99.0PERCENTILE",
                "subcomparator"=>nil,
                "type"=>"Standard",
                "value_alias"=>nil
              },
              {
                "keyspace_name"=>"system",
                "columnfamily_name"=>"hints",
                "bloom_filter_fp_chance"=>"0.01",
                "caching"=>"KEYS_ONLY",
                "column_aliases"=>"[\"hint_id\",\"message_version\"]",
                "comment"=>"hints awaiting delivery",
                "compaction_strategy_class"=>
                 "org.apache.cassandra.db.compaction.SizeTieredCompactionStrategy",
                "compaction_strategy_options"=>"{\"enabled\":\"false\"}",
                "comparator"=>
                 "org.apache.cassandra.db.marshal.CompositeType(org.apache.cassandra.db.marshal.TimeUUIDType,org.apache.cassandra.db.marshal.Int32Type)",
                "compression_parameters"=>
                 "{\"sstable_compression\":\"org.apache.cassandra.io.compress.LZ4Compressor\"}",
                "default_time_to_live"=>"0",
                "default_validator"=>"org.apache.cassandra.db.marshal.BytesType",
                "dropped_columns"=>nil,
                "gc_grace_seconds"=>"0",
                "index_interval"=>"128",
                "is_dense"=>"true",
                "key_aliases"=>"[\"target_id\"]",
                "key_validator"=>"org.apache.cassandra.db.marshal.UUIDType",
                "local_read_repair_chance"=>"0.0",
                "max_compaction_threshold"=>"32",
                "memtable_flush_period_in_ms"=>"3600000",
                "min_compaction_threshold"=>"4",
                "populate_io_cache_on_flush"=>"false",
                "read_repair_chance"=>"0.0",
                "replicate_on_write"=>"true",
                "speculative_retry"=>"99.0PERCENTILE",
                "subcomparator"=>nil,
                "type"=>"Standard",
                "value_alias"=>"mutation"
              },
              {
                "keyspace_name"=>"system",
                "columnfamily_name"=>"local",
                "bloom_filter_fp_chance"=>"0.01",
                "caching"=>"KEYS_ONLY",
                "column_aliases"=>"[]",
                "comment"=>"information about the local node",
                "compaction_strategy_class"=>
                 "org.apache.cassandra.db.compaction.SizeTieredCompactionStrategy",
                "compaction_strategy_options"=>"{}",
                "comparator"=>
                 "org.apache.cassandra.db.marshal.CompositeType(org.apache.cassandra.db.marshal.UTF8Type,org.apache.cassandra.db.marshal.ColumnToCollectionType(7472756e63617465645f6174:org.apache.cassandra.db.marshal.MapType(org.apache.cassandra.db.marshal.UUIDType,org.apache.cassandra.db.marshal.BytesType),746f6b656e73:org.apache.cassandra.db.marshal.SetType(org.apache.cassandra.db.marshal.UTF8Type)))",
                "compression_parameters"=>
                 "{\"sstable_compression\":\"org.apache.cassandra.io.compress.LZ4Compressor\"}",
                "default_time_to_live"=>"0",
                "default_validator"=>"org.apache.cassandra.db.marshal.BytesType",
                "dropped_columns"=>nil,
                "gc_grace_seconds"=>"0",
                "index_interval"=>"128",
                "is_dense"=>"false",
                "key_aliases"=>"[\"key\"]",
                "key_validator"=>"org.apache.cassandra.db.marshal.UTF8Type",
                "local_read_repair_chance"=>"0.0",
                "max_compaction_threshold"=>"32",
                "memtable_flush_period_in_ms"=>"3600000",
                "min_compaction_threshold"=>"4",
                "populate_io_cache_on_flush"=>"false",
                "read_repair_chance"=>"0.0",
                "replicate_on_write"=>"true",
                "speculative_retry"=>"99.0PERCENTILE",
                "subcomparator"=>nil,
                "type"=>"Standard",
                "value_alias"=>nil
              },
              {
                "keyspace_name"=>"system",
                "columnfamily_name"=>"paxos",
                "bloom_filter_fp_chance"=>"0.1",
                "caching"=>"KEYS_ONLY",
                "column_aliases"=>"[\"cf_id\"]",
                "comment"=>"in-progress paxos proposals",
                "compaction_strategy_class"=>
                 "org.apache.cassandra.db.compaction.LeveledCompactionStrategy",
                "compaction_strategy_options"=>"{}",
                "comparator"=>
                 "org.apache.cassandra.db.marshal.CompositeType(org.apache.cassandra.db.marshal.UUIDType,org.apache.cassandra.db.marshal.UTF8Type)",
                "compression_parameters"=>
                 "{\"sstable_compression\":\"org.apache.cassandra.io.compress.LZ4Compressor\"}",
                "default_time_to_live"=>"0",
                "default_validator"=>"org.apache.cassandra.db.marshal.BytesType",
                "dropped_columns"=>nil,
                "gc_grace_seconds"=>"0",
                "index_interval"=>"128",
                "is_dense"=>"false",
                "key_aliases"=>"[\"row_key\"]",
                "key_validator"=>"org.apache.cassandra.db.marshal.BytesType",
                "local_read_repair_chance"=>"0.0",
                "max_compaction_threshold"=>"32",
                "memtable_flush_period_in_ms"=>"3600000",
                "min_compaction_threshold"=>"4",
                "populate_io_cache_on_flush"=>"false",
                "read_repair_chance"=>"0.0",
                "replicate_on_write"=>"true",
                "speculative_retry"=>"99.0PERCENTILE",
                "subcomparator"=>nil,
                "type"=>"Standard",
                "value_alias"=>nil
              },
              {
                "keyspace_name"=>"system",
                "columnfamily_name"=>"peer_events",
                "bloom_filter_fp_chance"=>"0.01",
                "caching"=>"KEYS_ONLY",
                "column_aliases"=>"[]",
                "comment"=>"cf contains events related to peers",
                "compaction_strategy_class"=>
                 "org.apache.cassandra.db.compaction.SizeTieredCompactionStrategy",
                "compaction_strategy_options"=>"{}",
                "comparator"=>
                 "org.apache.cassandra.db.marshal.CompositeType(org.apache.cassandra.db.marshal.UTF8Type,org.apache.cassandra.db.marshal.ColumnToCollectionType(68696e74735f64726f70706564:org.apache.cassandra.db.marshal.MapType(org.apache.cassandra.db.marshal.UUIDType,org.apache.cassandra.db.marshal.Int32Type)))",
                "compression_parameters"=>
                 "{\"sstable_compression\":\"org.apache.cassandra.io.compress.LZ4Compressor\"}",
                "default_time_to_live"=>"0",
                "default_validator"=>"org.apache.cassandra.db.marshal.BytesType",
                "dropped_columns"=>nil,
                "gc_grace_seconds"=>"0",
                "index_interval"=>"128",
                "is_dense"=>"false",
                "key_aliases"=>"[\"peer\"]",
                "key_validator"=>"org.apache.cassandra.db.marshal.InetAddressType",
                "local_read_repair_chance"=>"0.0",
                "max_compaction_threshold"=>"32",
                "memtable_flush_period_in_ms"=>"3600000",
                "min_compaction_threshold"=>"4",
                "populate_io_cache_on_flush"=>"false",
                "read_repair_chance"=>"0.0",
                "replicate_on_write"=>"true",
                "speculative_retry"=>"99.0PERCENTILE",
                "subcomparator"=>nil,
                "type"=>"Standard",
                "value_alias"=>nil
              },
              {
                "keyspace_name"=>"system",
                "columnfamily_name"=>"peers",
                "bloom_filter_fp_chance"=>"0.01",
                "caching"=>"KEYS_ONLY",
                "column_aliases"=>"[]",
                "comment"=>"known peers in the cluster",
                "compaction_strategy_class"=>
                 "org.apache.cassandra.db.compaction.SizeTieredCompactionStrategy",
                "compaction_strategy_options"=>"{}",
                "comparator"=>
                 "org.apache.cassandra.db.marshal.CompositeType(org.apache.cassandra.db.marshal.UTF8Type,org.apache.cassandra.db.marshal.ColumnToCollectionType(746f6b656e73:org.apache.cassandra.db.marshal.SetType(org.apache.cassandra.db.marshal.UTF8Type)))",
                "compression_parameters"=>
                 "{\"sstable_compression\":\"org.apache.cassandra.io.compress.LZ4Compressor\"}",
                "default_time_to_live"=>"0",
                "default_validator"=>"org.apache.cassandra.db.marshal.BytesType",
                "dropped_columns"=>nil,
                "gc_grace_seconds"=>"0",
                "index_interval"=>"128",
                "is_dense"=>"false",
                "key_aliases"=>"[\"peer\"]",
                "key_validator"=>"org.apache.cassandra.db.marshal.InetAddressType",
                "local_read_repair_chance"=>"0.0",
                "max_compaction_threshold"=>"32",
                "memtable_flush_period_in_ms"=>"3600000",
                "min_compaction_threshold"=>"4",
                "populate_io_cache_on_flush"=>"false",
                "read_repair_chance"=>"0.0",
                "replicate_on_write"=>"true",
                "speculative_retry"=>"99.0PERCENTILE",
                "subcomparator"=>nil,
                "type"=>"Standard",
                "value_alias"=>nil
              },
              {
                "keyspace_name"=>"system",
                "columnfamily_name"=>"range_xfers",
                "bloom_filter_fp_chance"=>"0.01",
                "caching"=>"KEYS_ONLY",
                "column_aliases"=>"[]",
                "comment"=>"ranges requested for transfer here",
                "compaction_strategy_class"=>
                 "org.apache.cassandra.db.compaction.SizeTieredCompactionStrategy",
                "compaction_strategy_options"=>"{}",
                "comparator"=>
                 "org.apache.cassandra.db.marshal.CompositeType(org.apache.cassandra.db.marshal.UTF8Type)",
                "compression_parameters"=>
                 "{\"sstable_compression\":\"org.apache.cassandra.io.compress.LZ4Compressor\"}",
                "default_time_to_live"=>"0",
                "default_validator"=>"org.apache.cassandra.db.marshal.BytesType",
                "dropped_columns"=>nil,
                "gc_grace_seconds"=>"0",
                "index_interval"=>"128",
                "is_dense"=>"false",
                "key_aliases"=>"[\"token_bytes\"]",
                "key_validator"=>"org.apache.cassandra.db.marshal.BytesType",
                "local_read_repair_chance"=>"0.0",
                "max_compaction_threshold"=>"32",
                "memtable_flush_period_in_ms"=>"3600000",
                "min_compaction_threshold"=>"4",
                "populate_io_cache_on_flush"=>"false",
                "read_repair_chance"=>"0.0",
                "replicate_on_write"=>"true",
                "speculative_retry"=>"99.0PERCENTILE",
                "subcomparator"=>nil,
                "type"=>"Standard",
                "value_alias"=>nil
              },
              {
                "keyspace_name"=>"system",
                "columnfamily_name"=>"schema_columnfamilies",
                "bloom_filter_fp_chance"=>"0.01",
                "caching"=>"KEYS_ONLY",
                "column_aliases"=>"[\"columnfamily_name\"]",
                "comment"=>"ColumnFamily definitions",
                "compaction_strategy_class"=>
                 "org.apache.cassandra.db.compaction.SizeTieredCompactionStrategy",
                "compaction_strategy_options"=>"{}",
                "comparator"=>
                 "org.apache.cassandra.db.marshal.CompositeType(org.apache.cassandra.db.marshal.UTF8Type,org.apache.cassandra.db.marshal.UTF8Type,org.apache.cassandra.db.marshal.ColumnToCollectionType(64726f707065645f636f6c756d6e73:org.apache.cassandra.db.marshal.MapType(org.apache.cassandra.db.marshal.UTF8Type,org.apache.cassandra.db.marshal.LongType)))",
                "compression_parameters"=>
                 "{\"sstable_compression\":\"org.apache.cassandra.io.compress.LZ4Compressor\"}",
                "default_time_to_live"=>"0",
                "default_validator"=>"org.apache.cassandra.db.marshal.BytesType",
                "dropped_columns"=>nil,
                "gc_grace_seconds"=>"604800",
                "index_interval"=>"128",
                "is_dense"=>"false",
                "key_aliases"=>"[\"keyspace_name\"]",
                "key_validator"=>"org.apache.cassandra.db.marshal.UTF8Type",
                "local_read_repair_chance"=>"0.0",
                "max_compaction_threshold"=>"32",
                "memtable_flush_period_in_ms"=>"3600000",
                "min_compaction_threshold"=>"4",
                "populate_io_cache_on_flush"=>"false",
                "read_repair_chance"=>"0.0",
                "replicate_on_write"=>"true",
                "speculative_retry"=>"99.0PERCENTILE",
                "subcomparator"=>nil,
                "type"=>"Standard",
                "value_alias"=>nil
              },
              {
                "keyspace_name"=>"system",
                "columnfamily_name"=>"schema_columns",
                "bloom_filter_fp_chance"=>"0.01",
                "caching"=>"KEYS_ONLY",
                "column_aliases"=>"[\"columnfamily_name\",\"column_name\"]",
                "comment"=>"ColumnFamily column attributes",
                "compaction_strategy_class"=>
                 "org.apache.cassandra.db.compaction.SizeTieredCompactionStrategy",
                "compaction_strategy_options"=>"{}",
                "comparator"=>
                 "org.apache.cassandra.db.marshal.CompositeType(org.apache.cassandra.db.marshal.UTF8Type,org.apache.cassandra.db.marshal.UTF8Type,org.apache.cassandra.db.marshal.UTF8Type)",
                "compression_parameters"=>
                 "{\"sstable_compression\":\"org.apache.cassandra.io.compress.LZ4Compressor\"}",
                "default_time_to_live"=>"0",
                "default_validator"=>"org.apache.cassandra.db.marshal.BytesType",
                "dropped_columns"=>nil,
                "gc_grace_seconds"=>"604800",
                "index_interval"=>"128",
                "is_dense"=>"false",
                "key_aliases"=>"[\"keyspace_name\"]",
                "key_validator"=>"org.apache.cassandra.db.marshal.UTF8Type",
                "local_read_repair_chance"=>"0.0",
                "max_compaction_threshold"=>"32",
                "memtable_flush_period_in_ms"=>"3600000",
                "min_compaction_threshold"=>"4",
                "populate_io_cache_on_flush"=>"false",
                "read_repair_chance"=>"0.0",
                "replicate_on_write"=>"true",
                "speculative_retry"=>"99.0PERCENTILE",
                "subcomparator"=>nil,
                "type"=>"Standard",
                "value_alias"=>nil
              },
              {
                "keyspace_name"=>"system",
                "columnfamily_name"=>"schema_keyspaces",
                "bloom_filter_fp_chance"=>"0.01",
                "caching"=>"KEYS_ONLY",
                "column_aliases"=>"[]",
                "comment"=>"keyspace definitions",
                "compaction_strategy_class"=>
                 "org.apache.cassandra.db.compaction.SizeTieredCompactionStrategy",
                "compaction_strategy_options"=>"{}",
                "comparator"=>"org.apache.cassandra.db.marshal.UTF8Type",
                "compression_parameters"=>
                 "{\"sstable_compression\":\"org.apache.cassandra.io.compress.LZ4Compressor\"}",
                "default_time_to_live"=>"0",
                "default_validator"=>"org.apache.cassandra.db.marshal.BytesType",
                "dropped_columns"=>nil,
                "gc_grace_seconds"=>"604800",
                "index_interval"=>"128",
                "is_dense"=>"false",
                "key_aliases"=>"[\"keyspace_name\"]",
                "key_validator"=>"org.apache.cassandra.db.marshal.UTF8Type",
                "local_read_repair_chance"=>"0.0",
                "max_compaction_threshold"=>"32",
                "memtable_flush_period_in_ms"=>"3600000",
                "min_compaction_threshold"=>"4",
                "populate_io_cache_on_flush"=>"false",
                "read_repair_chance"=>"0.0",
                "replicate_on_write"=>"true",
                "speculative_retry"=>"99.0PERCENTILE",
                "subcomparator"=>nil,
                "type"=>"Standard",
                "value_alias"=>nil
              },
              {
                "keyspace_name"=>"system",
                "columnfamily_name"=>"schema_triggers",
                "bloom_filter_fp_chance"=>"0.01",
                "caching"=>"KEYS_ONLY",
                "column_aliases"=>"[\"columnfamily_name\",\"trigger_name\"]",
                "comment"=>"triggers metadata table",
                "compaction_strategy_class"=>
                 "org.apache.cassandra.db.compaction.SizeTieredCompactionStrategy",
                "compaction_strategy_options"=>"{}",
                "comparator"=>
                 "org.apache.cassandra.db.marshal.CompositeType(org.apache.cassandra.db.marshal.UTF8Type,org.apache.cassandra.db.marshal.UTF8Type,org.apache.cassandra.db.marshal.UTF8Type,org.apache.cassandra.db.marshal.ColumnToCollectionType(747269676765725f6f7074696f6e73:org.apache.cassandra.db.marshal.MapType(org.apache.cassandra.db.marshal.UTF8Type,org.apache.cassandra.db.marshal.UTF8Type)))",
                "compression_parameters"=>
                 "{\"sstable_compression\":\"org.apache.cassandra.io.compress.LZ4Compressor\"}",
                "default_time_to_live"=>"0",
                "default_validator"=>"org.apache.cassandra.db.marshal.BytesType",
                "dropped_columns"=>nil,
                "gc_grace_seconds"=>"604800",
                "index_interval"=>"128",
                "is_dense"=>"false",
                "key_aliases"=>"[\"keyspace_name\"]",
                "key_validator"=>"org.apache.cassandra.db.marshal.UTF8Type",
                "local_read_repair_chance"=>"0.0",
                "max_compaction_threshold"=>"32",
                "memtable_flush_period_in_ms"=>"3600000",
                "min_compaction_threshold"=>"4",
                "populate_io_cache_on_flush"=>"false",
                "read_repair_chance"=>"0.0",
                "replicate_on_write"=>"true",
                "speculative_retry"=>"99.0PERCENTILE",
                "subcomparator"=>nil,
                "type"=>"Standard",
                "value_alias"=>nil
              },
              {
                "keyspace_name"=>"system",
                "columnfamily_name"=>"sstable_activity",
                "bloom_filter_fp_chance"=>"0.01",
                "caching"=>"KEYS_ONLY",
                "column_aliases"=>"[]",
                "comment"=>"historic sstable read rates",
                "compaction_strategy_class"=>
                 "org.apache.cassandra.db.compaction.SizeTieredCompactionStrategy",
                "compaction_strategy_options"=>"{}",
                "comparator"=>
                 "org.apache.cassandra.db.marshal.CompositeType(org.apache.cassandra.db.marshal.UTF8Type)",
                "compression_parameters"=>
                 "{\"sstable_compression\":\"org.apache.cassandra.io.compress.LZ4Compressor\"}",
                "default_time_to_live"=>"0",
                "default_validator"=>"org.apache.cassandra.db.marshal.BytesType",
                "dropped_columns"=>nil,
                "gc_grace_seconds"=>"0",
                "index_interval"=>"128",
                "is_dense"=>"false",
                "key_aliases"=>"[\"keyspace_name\",\"columnfamily_name\",\"generation\"]",
                "key_validator"=>
                 "org.apache.cassandra.db.marshal.CompositeType(org.apache.cassandra.db.marshal.UTF8Type,org.apache.cassandra.db.marshal.UTF8Type,org.apache.cassandra.db.marshal.Int32Type)",
                "local_read_repair_chance"=>"0.0",
                "max_compaction_threshold"=>"32",
                "memtable_flush_period_in_ms"=>"3600000",
                "min_compaction_threshold"=>"4",
                "populate_io_cache_on_flush"=>"false",
                "read_repair_chance"=>"0.0",
                "replicate_on_write"=>"true",
                "speculative_retry"=>"99.0PERCENTILE",
                "subcomparator"=>nil,
                "type"=>"Standard",
                "value_alias"=>nil
              },
              {
                "keyspace_name"=>"system_traces",
                "columnfamily_name"=>"events",
                "bloom_filter_fp_chance"=>"0.01",
                "caching"=>"KEYS_ONLY",
                "column_aliases"=>"[\"event_id\"]",
                "comment"=>"",
                "compaction_strategy_class"=>
                 "org.apache.cassandra.db.compaction.SizeTieredCompactionStrategy",
                "compaction_strategy_options"=>"{}",
                "comparator"=>
                 "org.apache.cassandra.db.marshal.CompositeType(org.apache.cassandra.db.marshal.TimeUUIDType,org.apache.cassandra.db.marshal.UTF8Type)",
                "compression_parameters"=>
                 "{\"sstable_compression\":\"org.apache.cassandra.io.compress.LZ4Compressor\"}",
                "default_time_to_live"=>"0",
                "default_validator"=>"org.apache.cassandra.db.marshal.BytesType",
                "dropped_columns"=>nil,
                "gc_grace_seconds"=>"0",
                "index_interval"=>"128",
                "is_dense"=>"false",
                "key_aliases"=>"[\"session_id\"]",
                "key_validator"=>"org.apache.cassandra.db.marshal.UUIDType",
                "local_read_repair_chance"=>"0.0",
                "max_compaction_threshold"=>"32",
                "memtable_flush_period_in_ms"=>"3600000",
                "min_compaction_threshold"=>"4",
                "populate_io_cache_on_flush"=>"false",
                "read_repair_chance"=>"0.0",
                "replicate_on_write"=>"true",
                "speculative_retry"=>"99.0PERCENTILE",
                "subcomparator"=>nil,
                "type"=>"Standard",
                "value_alias"=>nil
              },
              {
                "keyspace_name"=>"system_traces",
                "columnfamily_name"=>"sessions",
                "bloom_filter_fp_chance"=>"0.01",
                "caching"=>"KEYS_ONLY",
                "column_aliases"=>"[]",
                "comment"=>"traced sessions",
                "compaction_strategy_class"=>
                 "org.apache.cassandra.db.compaction.SizeTieredCompactionStrategy",
                "compaction_strategy_options"=>"{}",
                "comparator"=>
                 "org.apache.cassandra.db.marshal.CompositeType(org.apache.cassandra.db.marshal.UTF8Type,org.apache.cassandra.db.marshal.ColumnToCollectionType(706172616d6574657273:org.apache.cassandra.db.marshal.MapType(org.apache.cassandra.db.marshal.UTF8Type,org.apache.cassandra.db.marshal.UTF8Type)))",
                "compression_parameters"=>
                 "{\"sstable_compression\":\"org.apache.cassandra.io.compress.LZ4Compressor\"}",
                "default_time_to_live"=>"0",
                "default_validator"=>"org.apache.cassandra.db.marshal.BytesType",
                "dropped_columns"=>nil,
                "gc_grace_seconds"=>"0",
                "index_interval"=>"128",
                "is_dense"=>"false",
                "key_aliases"=>"[\"session_id\"]",
                "key_validator"=>"org.apache.cassandra.db.marshal.UUIDType",
                "local_read_repair_chance"=>"0.0",
                "max_compaction_threshold"=>"32",
                "memtable_flush_period_in_ms"=>"3600000",
                "min_compaction_threshold"=>"4",
                "populate_io_cache_on_flush"=>"false",
                "read_repair_chance"=>"0.0",
                "replicate_on_write"=>"true",
                "speculative_retry"=>"99.0PERCENTILE",
                "subcomparator"=>nil,
                "type"=>"Standard",
                "value_alias"=>nil
              },
              {
                "keyspace_name"=>"simplex",
                "columnfamily_name"=>"songs",
                "bloom_filter_fp_chance"=>"0.01",
                "caching"=>"KEYS_ONLY",
                "column_aliases"=>"[]",
                "comment"=>"",
                "compaction_strategy_class"=>
                 "org.apache.cassandra.db.compaction.SizeTieredCompactionStrategy",
                "compaction_strategy_options"=>"{}",
                "comparator"=>
                 "org.apache.cassandra.db.marshal.CompositeType(org.apache.cassandra.db.marshal.UTF8Type,org.apache.cassandra.db.marshal.ColumnToCollectionType(74616773:org.apache.cassandra.db.marshal.SetType(org.apache.cassandra.db.marshal.UTF8Type)))",
                "compression_parameters"=>
                 "{\"sstable_compression\":\"org.apache.cassandra.io.compress.LZ4Compressor\"}",
                "default_time_to_live"=>"0",
                "default_validator"=>"org.apache.cassandra.db.marshal.BytesType",
                "dropped_columns"=>nil,
                "gc_grace_seconds"=>"864000",
                "index_interval"=>"128",
                "is_dense"=>"false",
                "key_aliases"=>"[\"id\"]",
                "key_validator"=>"org.apache.cassandra.db.marshal.UUIDType",
                "local_read_repair_chance"=>"0.1",
                "max_compaction_threshold"=>"32",
                "memtable_flush_period_in_ms"=>"0",
                "min_compaction_threshold"=>"4",
                "populate_io_cache_on_flush"=>"false",
                "read_repair_chance"=>"0.0",
                "replicate_on_write"=>"true",
                "speculative_retry"=>"99.0PERCENTILE",
                "subcomparator"=>nil,
                "type"=>"Standard",
                "value_alias"=>nil
              }
            ]
          }
          let(:columns) {
            [
              {
                "keyspace_name"=>"system",
                "columnfamily_name"=>"IndexInfo",
                "column_name"=>"",
                "component_index"=>nil,
                "index_name"=>nil,
                "index_options"=>nil,
                "index_type"=>nil,
                "type"=>"compact_value",
                "validator"=>"org.apache.cassandra.db.marshal.BytesType"
              },
              {
                "keyspace_name"=>"system",
                "columnfamily_name"=>"IndexInfo",
                "column_name"=>"index_name",
                "component_index"=>nil,
                "index_name"=>nil,
                "index_options"=>nil,
                "index_type"=>nil,
                "type"=>"clustering_key",
                "validator"=>"org.apache.cassandra.db.marshal.UTF8Type"
              },
              {
                "keyspace_name"=>"system",
                "columnfamily_name"=>"IndexInfo",
                "column_name"=>"table_name",
                "component_index"=>nil,
                "index_name"=>nil,
                "index_options"=>nil,
                "index_type"=>nil,
                "type"=>"partition_key",
                "validator"=>"org.apache.cassandra.db.marshal.UTF8Type"
              },
              {
                "keyspace_name"=>"system",
                "columnfamily_name"=>"NodeIdInfo",
                "column_name"=>"",
                "component_index"=>nil,
                "index_name"=>nil,
                "index_options"=>nil,
                "index_type"=>nil,
                "type"=>"compact_value",
                "validator"=>"org.apache.cassandra.db.marshal.BytesType"
              },
              {
                "keyspace_name"=>"system",
                "columnfamily_name"=>"NodeIdInfo",
                "column_name"=>"id",
                "component_index"=>nil,
                "index_name"=>nil,
                "index_options"=>nil,
                "index_type"=>nil,
                "type"=>"clustering_key",
                "validator"=>"org.apache.cassandra.db.marshal.TimeUUIDType"
              },
              {
                "keyspace_name"=>"system",
                "columnfamily_name"=>"NodeIdInfo",
                "column_name"=>"key",
                "component_index"=>nil,
                "index_name"=>nil,
                "index_options"=>nil,
                "index_type"=>nil,
                "type"=>"partition_key",
                "validator"=>"org.apache.cassandra.db.marshal.UTF8Type"
              },
              {
                "keyspace_name"=>"system",
                "columnfamily_name"=>"batchlog",
                "column_name"=>"data",
                "component_index"=>0,
                "index_name"=>nil,
                "index_options"=>nil,
                "index_type"=>nil,
                "type"=>"regular",
                "validator"=>"org.apache.cassandra.db.marshal.BytesType"
              },
              {
                "keyspace_name"=>"system",
                "columnfamily_name"=>"batchlog",
                "column_name"=>"id",
                "component_index"=>nil,
                "index_name"=>nil,
                "index_options"=>nil,
                "index_type"=>nil,
                "type"=>"partition_key",
                "validator"=>"org.apache.cassandra.db.marshal.UUIDType"
              },
              {
                "keyspace_name"=>"system",
                "columnfamily_name"=>"batchlog",
                "column_name"=>"version",
                "component_index"=>0,
                "index_name"=>nil,
                "index_options"=>nil,
                "index_type"=>nil,
                "type"=>"regular",
                "validator"=>"org.apache.cassandra.db.marshal.Int32Type"
              },
              {
                "keyspace_name"=>"system",
                "columnfamily_name"=>"batchlog",
                "column_name"=>"written_at",
                "component_index"=>0,
                "index_name"=>nil,
                "index_options"=>nil,
                "index_type"=>nil,
                "type"=>"regular",
                "validator"=>"org.apache.cassandra.db.marshal.TimestampType"
              },
              {
                "keyspace_name"=>"system",
                "columnfamily_name"=>"compaction_history",
                "column_name"=>"bytes_in",
                "component_index"=>0,
                "index_name"=>nil,
                "index_options"=>nil,
                "index_type"=>nil,
                "type"=>"regular",
                "validator"=>"org.apache.cassandra.db.marshal.LongType"
              },
              {
                "keyspace_name"=>"system",
                "columnfamily_name"=>"compaction_history",
                "column_name"=>"bytes_out",
                "component_index"=>0,
                "index_name"=>nil,
                "index_options"=>nil,
                "index_type"=>nil,
                "type"=>"regular",
                "validator"=>"org.apache.cassandra.db.marshal.LongType"
              },
              {
                "keyspace_name"=>"system",
                "columnfamily_name"=>"compaction_history",
                "column_name"=>"columnfamily_name",
                "component_index"=>0,
                "index_name"=>nil,
                "index_options"=>nil,
                "index_type"=>nil,
                "type"=>"regular",
                "validator"=>"org.apache.cassandra.db.marshal.UTF8Type"
              },
              {
                "keyspace_name"=>"system",
                "columnfamily_name"=>"compaction_history",
                "column_name"=>"compacted_at",
                "component_index"=>0,
                "index_name"=>nil,
                "index_options"=>nil,
                "index_type"=>nil,
                "type"=>"regular",
                "validator"=>"org.apache.cassandra.db.marshal.TimestampType"
              },
              {
                "keyspace_name"=>"system",
                "columnfamily_name"=>"compaction_history",
                "column_name"=>"id",
                "component_index"=>nil,
                "index_name"=>nil,
                "index_options"=>nil,
                "index_type"=>nil,
                "type"=>"partition_key",
                "validator"=>"org.apache.cassandra.db.marshal.UUIDType"
              },
              {
                "keyspace_name"=>"system",
                "columnfamily_name"=>"compaction_history",
                "column_name"=>"keyspace_name",
                "component_index"=>0,
                "index_name"=>nil,
                "index_options"=>nil,
                "index_type"=>nil,
                "type"=>"regular",
                "validator"=>"org.apache.cassandra.db.marshal.UTF8Type"
              },
              {
                "keyspace_name"=>"system",
                "columnfamily_name"=>"compaction_history",
                "column_name"=>"rows_merged",
                "component_index"=>0,
                "index_name"=>nil,
                "index_options"=>nil,
                "index_type"=>nil,
                "type"=>"regular",
                "validator"=>
                 "org.apache.cassandra.db.marshal.MapType(org.apache.cassandra.db.marshal.Int32Type,org.apache.cassandra.db.marshal.LongType)"
              },
              {
                "keyspace_name"=>"system",
                "columnfamily_name"=>"compactions_in_progress",
                "column_name"=>"columnfamily_name",
                "component_index"=>0,
                "index_name"=>nil,
                "index_options"=>nil,
                "index_type"=>nil,
                "type"=>"regular",
                "validator"=>"org.apache.cassandra.db.marshal.UTF8Type"
              },
              {
                "keyspace_name"=>"system",
                "columnfamily_name"=>"compactions_in_progress",
                "column_name"=>"id",
                "component_index"=>nil,
                "index_name"=>nil,
                "index_options"=>nil,
                "index_type"=>nil,
                "type"=>"partition_key",
                "validator"=>"org.apache.cassandra.db.marshal.UUIDType"
              },
              {
                "keyspace_name"=>"system",
                "columnfamily_name"=>"compactions_in_progress",
                "column_name"=>"inputs",
                "component_index"=>0,
                "index_name"=>nil,
                "index_options"=>nil,
                "index_type"=>nil,
                "type"=>"regular",
                "validator"=>
                 "org.apache.cassandra.db.marshal.SetType(org.apache.cassandra.db.marshal.Int32Type)"
              },
              {
                "keyspace_name"=>"system",
                "columnfamily_name"=>"compactions_in_progress",
                "column_name"=>"keyspace_name",
                "component_index"=>0,
                "index_name"=>nil,
                "index_options"=>nil,
                "index_type"=>nil,
                "type"=>"regular",
                "validator"=>"org.apache.cassandra.db.marshal.UTF8Type"
              },
              {
                "keyspace_name"=>"system",
                "columnfamily_name"=>"hints",
                "column_name"=>"hint_id",
                "component_index"=>0,
                "index_name"=>nil,
                "index_options"=>nil,
                "index_type"=>nil,
                "type"=>"clustering_key",
                "validator"=>"org.apache.cassandra.db.marshal.TimeUUIDType"
              },
              {
                "keyspace_name"=>"system",
                "columnfamily_name"=>"hints",
                "column_name"=>"message_version",
                "component_index"=>1,
                "index_name"=>nil,
                "index_options"=>nil,
                "index_type"=>nil,
                "type"=>"clustering_key",
                "validator"=>"org.apache.cassandra.db.marshal.Int32Type"
              },
              {
                "keyspace_name"=>"system",
                "columnfamily_name"=>"hints",
                "column_name"=>"mutation",
                "component_index"=>nil,
                "index_name"=>nil,
                "index_options"=>nil,
                "index_type"=>nil,
                "type"=>"compact_value",
                "validator"=>"org.apache.cassandra.db.marshal.BytesType"
              },
              {
                "keyspace_name"=>"system",
                "columnfamily_name"=>"hints",
                "column_name"=>"target_id",
                "component_index"=>nil,
                "index_name"=>nil,
                "index_options"=>nil,
                "index_type"=>nil,
                "type"=>"partition_key",
                "validator"=>"org.apache.cassandra.db.marshal.UUIDType"
              },
              {
                "keyspace_name"=>"system",
                "columnfamily_name"=>"local",
                "column_name"=>"bootstrapped",
                "component_index"=>0,
                "index_name"=>nil,
                "index_options"=>nil,
                "index_type"=>nil,
                "type"=>"regular",
                "validator"=>"org.apache.cassandra.db.marshal.UTF8Type"
              },
              {
                "keyspace_name"=>"system",
                "columnfamily_name"=>"local",
                "column_name"=>"cluster_name",
                "component_index"=>0,
                "index_name"=>nil,
                "index_options"=>nil,
                "index_type"=>nil,
                "type"=>"regular",
                "validator"=>"org.apache.cassandra.db.marshal.UTF8Type"
              },
              {
                "keyspace_name"=>"system",
                "columnfamily_name"=>"local",
                "column_name"=>"cql_version",
                "component_index"=>0,
                "index_name"=>nil,
                "index_options"=>nil,
                "index_type"=>nil,
                "type"=>"regular",
                "validator"=>"org.apache.cassandra.db.marshal.UTF8Type"
              },
              {
                "keyspace_name"=>"system",
                "columnfamily_name"=>"local",
                "column_name"=>"data_center",
                "component_index"=>0,
                "index_name"=>nil,
                "index_options"=>nil,
                "index_type"=>nil,
                "type"=>"regular",
                "validator"=>"org.apache.cassandra.db.marshal.UTF8Type"
              },
              {
                "keyspace_name"=>"system",
                "columnfamily_name"=>"local",
                "column_name"=>"gossip_generation",
                "component_index"=>0,
                "index_name"=>nil,
                "index_options"=>nil,
                "index_type"=>nil,
                "type"=>"regular",
                "validator"=>"org.apache.cassandra.db.marshal.Int32Type"
              },
              {
                "keyspace_name"=>"system",
                "columnfamily_name"=>"local",
                "column_name"=>"host_id",
                "component_index"=>0,
                "index_name"=>nil,
                "index_options"=>nil,
                "index_type"=>nil,
                "type"=>"regular",
                "validator"=>"org.apache.cassandra.db.marshal.UUIDType"
              },
              {
                "keyspace_name"=>"system",
                "columnfamily_name"=>"local",
                "column_name"=>"key",
                "component_index"=>nil,
                "index_name"=>nil,
                "index_options"=>nil,
                "index_type"=>nil,
                "type"=>"partition_key",
                "validator"=>"org.apache.cassandra.db.marshal.UTF8Type"
              },
              {
                "keyspace_name"=>"system",
                "columnfamily_name"=>"local",
                "column_name"=>"native_protocol_version",
                "component_index"=>0,
                "index_name"=>nil,
                "index_options"=>nil,
                "index_type"=>nil,
                "type"=>"regular",
                "validator"=>"org.apache.cassandra.db.marshal.UTF8Type"
              },
              {
                "keyspace_name"=>"system",
                "columnfamily_name"=>"local",
                "column_name"=>"partitioner",
                "component_index"=>0,
                "index_name"=>nil,
                "index_options"=>nil,
                "index_type"=>nil,
                "type"=>"regular",
                "validator"=>"org.apache.cassandra.db.marshal.UTF8Type"
              },
              {
                "keyspace_name"=>"system",
                "columnfamily_name"=>"local",
                "column_name"=>"rack",
                "component_index"=>0,
                "index_name"=>nil,
                "index_options"=>nil,
                "index_type"=>nil,
                "type"=>"regular",
                "validator"=>"org.apache.cassandra.db.marshal.UTF8Type"
              },
              {
                "keyspace_name"=>"system",
                "columnfamily_name"=>"local",
                "column_name"=>"release_version",
                "component_index"=>0,
                "index_name"=>nil,
                "index_options"=>nil,
                "index_type"=>nil,
                "type"=>"regular",
                "validator"=>"org.apache.cassandra.db.marshal.UTF8Type"
              },
              {
                "keyspace_name"=>"system",
                "columnfamily_name"=>"local",
                "column_name"=>"schema_version",
                "component_index"=>0,
                "index_name"=>nil,
                "index_options"=>nil,
                "index_type"=>nil,
                "type"=>"regular",
                "validator"=>"org.apache.cassandra.db.marshal.UUIDType"
              },
              {
                "keyspace_name"=>"system",
                "columnfamily_name"=>"local",
                "column_name"=>"thrift_version",
                "component_index"=>0,
                "index_name"=>nil,
                "index_options"=>nil,
                "index_type"=>nil,
                "type"=>"regular",
                "validator"=>"org.apache.cassandra.db.marshal.UTF8Type"
              },
              {
                "keyspace_name"=>"system",
                "columnfamily_name"=>"local",
                "column_name"=>"tokens",
                "component_index"=>0,
                "index_name"=>nil,
                "index_options"=>nil,
                "index_type"=>nil,
                "type"=>"regular",
                "validator"=>
                 "org.apache.cassandra.db.marshal.SetType(org.apache.cassandra.db.marshal.UTF8Type)"
              },
              {
                "keyspace_name"=>"system",
                "columnfamily_name"=>"local",
                "column_name"=>"truncated_at",
                "component_index"=>0,
                "index_name"=>nil,
                "index_options"=>nil,
                "index_type"=>nil,
                "type"=>"regular",
                "validator"=>
                 "org.apache.cassandra.db.marshal.MapType(org.apache.cassandra.db.marshal.UUIDType,org.apache.cassandra.db.marshal.BytesType)"
              },
              {
                "keyspace_name"=>"system",
                "columnfamily_name"=>"paxos",
                "column_name"=>"cf_id",
                "component_index"=>0,
                "index_name"=>nil,
                "index_options"=>nil,
                "index_type"=>nil,
                "type"=>"clustering_key",
                "validator"=>"org.apache.cassandra.db.marshal.UUIDType"
              },
              {
                "keyspace_name"=>"system",
                "columnfamily_name"=>"paxos",
                "column_name"=>"in_progress_ballot",
                "component_index"=>1,
                "index_name"=>nil,
                "index_options"=>nil,
                "index_type"=>nil,
                "type"=>"regular",
                "validator"=>"org.apache.cassandra.db.marshal.TimeUUIDType"
              },
              {
                "keyspace_name"=>"system",
                "columnfamily_name"=>"paxos",
                "column_name"=>"most_recent_commit",
                "component_index"=>1,
                "index_name"=>nil,
                "index_options"=>nil,
                "index_type"=>nil,
                "type"=>"regular",
                "validator"=>"org.apache.cassandra.db.marshal.BytesType"
              },
              {
                "keyspace_name"=>"system",
                "columnfamily_name"=>"paxos",
                "column_name"=>"most_recent_commit_at",
                "component_index"=>1,
                "index_name"=>nil,
                "index_options"=>nil,
                "index_type"=>nil,
                "type"=>"regular",
                "validator"=>"org.apache.cassandra.db.marshal.TimeUUIDType"
              },
              {
                "keyspace_name"=>"system",
                "columnfamily_name"=>"paxos",
                "column_name"=>"proposal",
                "component_index"=>1,
                "index_name"=>nil,
                "index_options"=>nil,
                "index_type"=>nil,
                "type"=>"regular",
                "validator"=>"org.apache.cassandra.db.marshal.BytesType"
              },
              {
                "keyspace_name"=>"system",
                "columnfamily_name"=>"paxos",
                "column_name"=>"proposal_ballot",
                "component_index"=>1,
                "index_name"=>nil,
                "index_options"=>nil,
                "index_type"=>nil,
                "type"=>"regular",
                "validator"=>"org.apache.cassandra.db.marshal.TimeUUIDType"
              },
              {
                "keyspace_name"=>"system",
                "columnfamily_name"=>"paxos",
                "column_name"=>"row_key",
                "component_index"=>nil,
                "index_name"=>nil,
                "index_options"=>nil,
                "index_type"=>nil,
                "type"=>"partition_key",
                "validator"=>"org.apache.cassandra.db.marshal.BytesType"
              },
              {
                "keyspace_name"=>"system",
                "columnfamily_name"=>"peer_events",
                "column_name"=>"hints_dropped",
                "component_index"=>0,
                "index_name"=>nil,
                "index_options"=>nil,
                "index_type"=>nil,
                "type"=>"regular",
                "validator"=>
                 "org.apache.cassandra.db.marshal.MapType(org.apache.cassandra.db.marshal.UUIDType,org.apache.cassandra.db.marshal.Int32Type)"
              },
              {
                "keyspace_name"=>"system",
                "columnfamily_name"=>"peer_events",
                "column_name"=>"peer",
                "component_index"=>nil,
                "index_name"=>nil,
                "index_options"=>nil,
                "index_type"=>nil,
                "type"=>"partition_key",
                "validator"=>"org.apache.cassandra.db.marshal.InetAddressType"
              },
              {
                "keyspace_name"=>"system",
                "columnfamily_name"=>"peers",
                "column_name"=>"data_center",
                "component_index"=>0,
                "index_name"=>nil,
                "index_options"=>nil,
                "index_type"=>nil,
                "type"=>"regular",
                "validator"=>"org.apache.cassandra.db.marshal.UTF8Type"
              },
              {
                "keyspace_name"=>"system",
                "columnfamily_name"=>"peers",
                "column_name"=>"host_id",
                "component_index"=>0,
                "index_name"=>nil,
                "index_options"=>nil,
                "index_type"=>nil,
                "type"=>"regular",
                "validator"=>"org.apache.cassandra.db.marshal.UUIDType"
              },
              {
                "keyspace_name"=>"system",
                "columnfamily_name"=>"peers",
                "column_name"=>"peer",
                "component_index"=>nil,
                "index_name"=>nil,
                "index_options"=>nil,
                "index_type"=>nil,
                "type"=>"partition_key",
                "validator"=>"org.apache.cassandra.db.marshal.InetAddressType"
              },
              {
                "keyspace_name"=>"system",
                "columnfamily_name"=>"peers",
                "column_name"=>"preferred_ip",
                "component_index"=>0,
                "index_name"=>nil,
                "index_options"=>nil,
                "index_type"=>nil,
                "type"=>"regular",
                "validator"=>"org.apache.cassandra.db.marshal.InetAddressType"
              },
              {
                "keyspace_name"=>"system",
                "columnfamily_name"=>"peers",
                "column_name"=>"rack",
                "component_index"=>0,
                "index_name"=>nil,
                "index_options"=>nil,
                "index_type"=>nil,
                "type"=>"regular",
                "validator"=>"org.apache.cassandra.db.marshal.UTF8Type"
              },
              {
                "keyspace_name"=>"system",
                "columnfamily_name"=>"peers",
                "column_name"=>"release_version",
                "component_index"=>0,
                "index_name"=>nil,
                "index_options"=>nil,
                "index_type"=>nil,
                "type"=>"regular",
                "validator"=>"org.apache.cassandra.db.marshal.UTF8Type"
              },
              {
                "keyspace_name"=>"system",
                "columnfamily_name"=>"peers",
                "column_name"=>"rpc_address",
                "component_index"=>0,
                "index_name"=>nil,
                "index_options"=>nil,
                "index_type"=>nil,
                "type"=>"regular",
                "validator"=>"org.apache.cassandra.db.marshal.InetAddressType"
              },
              {
                "keyspace_name"=>"system",
                "columnfamily_name"=>"peers",
                "column_name"=>"schema_version",
                "component_index"=>0,
                "index_name"=>nil,
                "index_options"=>nil,
                "index_type"=>nil,
                "type"=>"regular",
                "validator"=>"org.apache.cassandra.db.marshal.UUIDType"
              },
              {
                "keyspace_name"=>"system",
                "columnfamily_name"=>"peers",
                "column_name"=>"tokens",
                "component_index"=>0,
                "index_name"=>nil,
                "index_options"=>nil,
                "index_type"=>nil,
                "type"=>"regular",
                "validator"=>
                 "org.apache.cassandra.db.marshal.SetType(org.apache.cassandra.db.marshal.UTF8Type)"
              },
              {
                "keyspace_name"=>"system",
                "columnfamily_name"=>"range_xfers",
                "column_name"=>"requested_at",
                "component_index"=>0,
                "index_name"=>nil,
                "index_options"=>nil,
                "index_type"=>nil,
                "type"=>"regular",
                "validator"=>"org.apache.cassandra.db.marshal.TimestampType"
              },
              {
                "keyspace_name"=>"system",
                "columnfamily_name"=>"range_xfers",
                "column_name"=>"token_bytes",
                "component_index"=>nil,
                "index_name"=>nil,
                "index_options"=>nil,
                "index_type"=>nil,
                "type"=>"partition_key",
                "validator"=>"org.apache.cassandra.db.marshal.BytesType"
              },
              {
                "keyspace_name"=>"system",
                "columnfamily_name"=>"schema_columnfamilies",
                "column_name"=>"bloom_filter_fp_chance",
                "component_index"=>1,
                "index_name"=>nil,
                "index_options"=>nil,
                "index_type"=>nil,
                "type"=>"regular",
                "validator"=>"org.apache.cassandra.db.marshal.DoubleType"
              },
              {
                "keyspace_name"=>"system",
                "columnfamily_name"=>"schema_columnfamilies",
                "column_name"=>"caching",
                "component_index"=>1,
                "index_name"=>nil,
                "index_options"=>nil,
                "index_type"=>nil,
                "type"=>"regular",
                "validator"=>"org.apache.cassandra.db.marshal.UTF8Type"
              },
              {
                "keyspace_name"=>"system",
                "columnfamily_name"=>"schema_columnfamilies",
                "column_name"=>"column_aliases",
                "component_index"=>1,
                "index_name"=>nil,
                "index_options"=>nil,
                "index_type"=>nil,
                "type"=>"regular",
                "validator"=>"org.apache.cassandra.db.marshal.UTF8Type"
              },
              {
                "keyspace_name"=>"system",
                "columnfamily_name"=>"schema_columnfamilies",
                "column_name"=>"columnfamily_name",
                "component_index"=>0,
                "index_name"=>nil,
                "index_options"=>nil,
                "index_type"=>nil,
                "type"=>"clustering_key",
                "validator"=>"org.apache.cassandra.db.marshal.UTF8Type"
              },
              {
                "keyspace_name"=>"system",
                "columnfamily_name"=>"schema_columnfamilies",
                "column_name"=>"comment",
                "component_index"=>1,
                "index_name"=>nil,
                "index_options"=>nil,
                "index_type"=>nil,
                "type"=>"regular",
                "validator"=>"org.apache.cassandra.db.marshal.UTF8Type"
              },
              {
                "keyspace_name"=>"system",
                "columnfamily_name"=>"schema_columnfamilies",
                "column_name"=>"compaction_strategy_class",
                "component_index"=>1,
                "index_name"=>nil,
                "index_options"=>nil,
                "index_type"=>nil,
                "type"=>"regular",
                "validator"=>"org.apache.cassandra.db.marshal.UTF8Type"
              },
              {
                "keyspace_name"=>"system",
                "columnfamily_name"=>"schema_columnfamilies",
                "column_name"=>"compaction_strategy_options",
                "component_index"=>1,
                "index_name"=>nil,
                "index_options"=>nil,
                "index_type"=>nil,
                "type"=>"regular",
                "validator"=>"org.apache.cassandra.db.marshal.UTF8Type"
              },
              {
                "keyspace_name"=>"system",
                "columnfamily_name"=>"schema_columnfamilies",
                "column_name"=>"comparator",
                "component_index"=>1,
                "index_name"=>nil,
                "index_options"=>nil,
                "index_type"=>nil,
                "type"=>"regular",
                "validator"=>"org.apache.cassandra.db.marshal.UTF8Type"
              },
              {
                "keyspace_name"=>"system",
                "columnfamily_name"=>"schema_columnfamilies",
                "column_name"=>"compression_parameters",
                "component_index"=>1,
                "index_name"=>nil,
                "index_options"=>nil,
                "index_type"=>nil,
                "type"=>"regular",
                "validator"=>"org.apache.cassandra.db.marshal.UTF8Type"
              },
              {
                "keyspace_name"=>"system",
                "columnfamily_name"=>"schema_columnfamilies",
                "column_name"=>"default_time_to_live",
                "component_index"=>1,
                "index_name"=>nil,
                "index_options"=>nil,
                "index_type"=>nil,
                "type"=>"regular",
                "validator"=>"org.apache.cassandra.db.marshal.Int32Type"
              },
              {
                "keyspace_name"=>"system",
                "columnfamily_name"=>"schema_columnfamilies",
                "column_name"=>"default_validator",
                "component_index"=>1,
                "index_name"=>nil,
                "index_options"=>nil,
                "index_type"=>nil,
                "type"=>"regular",
                "validator"=>"org.apache.cassandra.db.marshal.UTF8Type"
              },
              {
                "keyspace_name"=>"system",
                "columnfamily_name"=>"schema_columnfamilies",
                "column_name"=>"dropped_columns",
                "component_index"=>1,
                "index_name"=>nil,
                "index_options"=>nil,
                "index_type"=>nil,
                "type"=>"regular",
                "validator"=>
                 "org.apache.cassandra.db.marshal.MapType(org.apache.cassandra.db.marshal.UTF8Type,org.apache.cassandra.db.marshal.LongType)"
              },
              {
                "keyspace_name"=>"system",
                "columnfamily_name"=>"schema_columnfamilies",
                "column_name"=>"gc_grace_seconds",
                "component_index"=>1,
                "index_name"=>nil,
                "index_options"=>nil,
                "index_type"=>nil,
                "type"=>"regular",
                "validator"=>"org.apache.cassandra.db.marshal.Int32Type"
              },
              {
                "keyspace_name"=>"system",
                "columnfamily_name"=>"schema_columnfamilies",
                "column_name"=>"index_interval",
                "component_index"=>1,
                "index_name"=>nil,
                "index_options"=>nil,
                "index_type"=>nil,
                "type"=>"regular",
                "validator"=>"org.apache.cassandra.db.marshal.Int32Type"
              },
              {
                "keyspace_name"=>"system",
                "columnfamily_name"=>"schema_columnfamilies",
                "column_name"=>"is_dense",
                "component_index"=>1,
                "index_name"=>nil,
                "index_options"=>nil,
                "index_type"=>nil,
                "type"=>"regular",
                "validator"=>"org.apache.cassandra.db.marshal.BooleanType"
              },
              {
                "keyspace_name"=>"system",
                "columnfamily_name"=>"schema_columnfamilies",
                "column_name"=>"key_aliases",
                "component_index"=>1,
                "index_name"=>nil,
                "index_options"=>nil,
                "index_type"=>nil,
                "type"=>"regular",
                "validator"=>"org.apache.cassandra.db.marshal.UTF8Type"
              },
              {
                "keyspace_name"=>"system",
                "columnfamily_name"=>"schema_columnfamilies",
                "column_name"=>"key_validator",
                "component_index"=>1,
                "index_name"=>nil,
                "index_options"=>nil,
                "index_type"=>nil,
                "type"=>"regular",
                "validator"=>"org.apache.cassandra.db.marshal.UTF8Type"
              },
              {
                "keyspace_name"=>"system",
                "columnfamily_name"=>"schema_columnfamilies",
                "column_name"=>"keyspace_name",
                "component_index"=>nil,
                "index_name"=>nil,
                "index_options"=>nil,
                "index_type"=>nil,
                "type"=>"partition_key",
                "validator"=>"org.apache.cassandra.db.marshal.UTF8Type"
              },
              {
                "keyspace_name"=>"system",
                "columnfamily_name"=>"schema_columnfamilies",
                "column_name"=>"local_read_repair_chance",
                "component_index"=>1,
                "index_name"=>nil,
                "index_options"=>nil,
                "index_type"=>nil,
                "type"=>"regular",
                "validator"=>"org.apache.cassandra.db.marshal.DoubleType"
              },
              {
                "keyspace_name"=>"system",
                "columnfamily_name"=>"schema_columnfamilies",
                "column_name"=>"max_compaction_threshold",
                "component_index"=>1,
                "index_name"=>nil,
                "index_options"=>nil,
                "index_type"=>nil,
                "type"=>"regular",
                "validator"=>"org.apache.cassandra.db.marshal.Int32Type"
              },
              {
                "keyspace_name"=>"system",
                "columnfamily_name"=>"schema_columnfamilies",
                "column_name"=>"memtable_flush_period_in_ms",
                "component_index"=>1,
                "index_name"=>nil,
                "index_options"=>nil,
                "index_type"=>nil,
                "type"=>"regular",
                "validator"=>"org.apache.cassandra.db.marshal.Int32Type"
              },
              {
                "keyspace_name"=>"system",
                "columnfamily_name"=>"schema_columnfamilies",
                "column_name"=>"min_compaction_threshold",
                "component_index"=>1,
                "index_name"=>nil,
                "index_options"=>nil,
                "index_type"=>nil,
                "type"=>"regular",
                "validator"=>"org.apache.cassandra.db.marshal.Int32Type"
              },
              {
                "keyspace_name"=>"system",
                "columnfamily_name"=>"schema_columnfamilies",
                "column_name"=>"populate_io_cache_on_flush",
                "component_index"=>1,
                "index_name"=>nil,
                "index_options"=>nil,
                "index_type"=>nil,
                "type"=>"regular",
                "validator"=>"org.apache.cassandra.db.marshal.BooleanType"
              },
              {
                "keyspace_name"=>"system",
                "columnfamily_name"=>"schema_columnfamilies",
                "column_name"=>"read_repair_chance",
                "component_index"=>1,
                "index_name"=>nil,
                "index_options"=>nil,
                "index_type"=>nil,
                "type"=>"regular",
                "validator"=>"org.apache.cassandra.db.marshal.DoubleType"
              },
              {
                "keyspace_name"=>"system",
                "columnfamily_name"=>"schema_columnfamilies",
                "column_name"=>"replicate_on_write",
                "component_index"=>1,
                "index_name"=>nil,
                "index_options"=>nil,
                "index_type"=>nil,
                "type"=>"regular",
                "validator"=>"org.apache.cassandra.db.marshal.BooleanType"
              },
              {
                "keyspace_name"=>"system",
                "columnfamily_name"=>"schema_columnfamilies",
                "column_name"=>"speculative_retry",
                "component_index"=>1,
                "index_name"=>nil,
                "index_options"=>nil,
                "index_type"=>nil,
                "type"=>"regular",
                "validator"=>"org.apache.cassandra.db.marshal.UTF8Type"
              },
              {
                "keyspace_name"=>"system",
                "columnfamily_name"=>"schema_columnfamilies",
                "column_name"=>"subcomparator",
                "component_index"=>1,
                "index_name"=>nil,
                "index_options"=>nil,
                "index_type"=>nil,
                "type"=>"regular",
                "validator"=>"org.apache.cassandra.db.marshal.UTF8Type"
              },
              {
                "keyspace_name"=>"system",
                "columnfamily_name"=>"schema_columnfamilies",
                "column_name"=>"type",
                "component_index"=>1,
                "index_name"=>nil,
                "index_options"=>nil,
                "index_type"=>nil,
                "type"=>"regular",
                "validator"=>"org.apache.cassandra.db.marshal.UTF8Type"
              },
              {
                "keyspace_name"=>"system",
                "columnfamily_name"=>"schema_columnfamilies",
                "column_name"=>"value_alias",
                "component_index"=>1,
                "index_name"=>nil,
                "index_options"=>nil,
                "index_type"=>nil,
                "type"=>"regular",
                "validator"=>"org.apache.cassandra.db.marshal.UTF8Type"
              },
              {
                "keyspace_name"=>"system",
                "columnfamily_name"=>"schema_columns",
                "column_name"=>"column_name",
                "component_index"=>1,
                "index_name"=>nil,
                "index_options"=>nil,
                "index_type"=>nil,
                "type"=>"clustering_key",
                "validator"=>"org.apache.cassandra.db.marshal.UTF8Type"
              },
              {
                "keyspace_name"=>"system",
                "columnfamily_name"=>"schema_columns",
                "column_name"=>"columnfamily_name",
                "component_index"=>0,
                "index_name"=>nil,
                "index_options"=>nil,
                "index_type"=>nil,
                "type"=>"clustering_key",
                "validator"=>"org.apache.cassandra.db.marshal.UTF8Type"
              },
              {
                "keyspace_name"=>"system",
                "columnfamily_name"=>"schema_columns",
                "column_name"=>"component_index",
                "component_index"=>2,
                "index_name"=>nil,
                "index_options"=>nil,
                "index_type"=>nil,
                "type"=>"regular",
                "validator"=>"org.apache.cassandra.db.marshal.Int32Type"
              },
              {
                "keyspace_name"=>"system",
                "columnfamily_name"=>"schema_columns",
                "column_name"=>"index_name",
                "component_index"=>2,
                "index_name"=>nil,
                "index_options"=>nil,
                "index_type"=>nil,
                "type"=>"regular",
                "validator"=>"org.apache.cassandra.db.marshal.UTF8Type"
              },
              {
                "keyspace_name"=>"system",
                "columnfamily_name"=>"schema_columns",
                "column_name"=>"index_options",
                "component_index"=>2,
                "index_name"=>nil,
                "index_options"=>nil,
                "index_type"=>nil,
                "type"=>"regular",
                "validator"=>"org.apache.cassandra.db.marshal.UTF8Type"
              },
              {
                "keyspace_name"=>"system",
                "columnfamily_name"=>"schema_columns",
                "column_name"=>"index_type",
                "component_index"=>2,
                "index_name"=>nil,
                "index_options"=>nil,
                "index_type"=>nil,
                "type"=>"regular",
                "validator"=>"org.apache.cassandra.db.marshal.UTF8Type"
              },
              {
                "keyspace_name"=>"system",
                "columnfamily_name"=>"schema_columns",
                "column_name"=>"keyspace_name",
                "component_index"=>nil,
                "index_name"=>nil,
                "index_options"=>nil,
                "index_type"=>nil,
                "type"=>"partition_key",
                "validator"=>"org.apache.cassandra.db.marshal.UTF8Type"
              },
              {
                "keyspace_name"=>"system",
                "columnfamily_name"=>"schema_columns",
                "column_name"=>"type",
                "component_index"=>2,
                "index_name"=>nil,
                "index_options"=>nil,
                "index_type"=>nil,
                "type"=>"regular",
                "validator"=>"org.apache.cassandra.db.marshal.UTF8Type"
              },
              {
                "keyspace_name"=>"system",
                "columnfamily_name"=>"schema_columns",
                "column_name"=>"validator",
                "component_index"=>2,
                "index_name"=>nil,
                "index_options"=>nil,
                "index_type"=>nil,
                "type"=>"regular",
                "validator"=>"org.apache.cassandra.db.marshal.UTF8Type"
              },
              {
                "keyspace_name"=>"system",
                "columnfamily_name"=>"schema_keyspaces",
                "column_name"=>"durable_writes",
                "component_index"=>nil,
                "index_name"=>nil,
                "index_options"=>nil,
                "index_type"=>nil,
                "type"=>"regular",
                "validator"=>"org.apache.cassandra.db.marshal.BooleanType"
              },
              {
                "keyspace_name"=>"system",
                "columnfamily_name"=>"schema_keyspaces",
                "column_name"=>"keyspace_name",
                "component_index"=>nil,
                "index_name"=>nil,
                "index_options"=>nil,
                "index_type"=>nil,
                "type"=>"partition_key",
                "validator"=>"org.apache.cassandra.db.marshal.UTF8Type"
              },
              {
                "keyspace_name"=>"system",
                "columnfamily_name"=>"schema_keyspaces",
                "column_name"=>"strategy_class",
                "component_index"=>nil,
                "index_name"=>nil,
                "index_options"=>nil,
                "index_type"=>nil,
                "type"=>"regular",
                "validator"=>"org.apache.cassandra.db.marshal.UTF8Type"
              },
              {
                "keyspace_name"=>"system",
                "columnfamily_name"=>"schema_keyspaces",
                "column_name"=>"strategy_options",
                "component_index"=>nil,
                "index_name"=>nil,
                "index_options"=>nil,
                "index_type"=>nil,
                "type"=>"regular",
                "validator"=>"org.apache.cassandra.db.marshal.UTF8Type"
              },
              {
                "keyspace_name"=>"system",
                "columnfamily_name"=>"schema_triggers",
                "column_name"=>"columnfamily_name",
                "component_index"=>0,
                "index_name"=>nil,
                "index_options"=>nil,
                "index_type"=>nil,
                "type"=>"clustering_key",
                "validator"=>"org.apache.cassandra.db.marshal.UTF8Type"
              },
              {
                "keyspace_name"=>"system",
                "columnfamily_name"=>"schema_triggers",
                "column_name"=>"keyspace_name",
                "component_index"=>nil,
                "index_name"=>nil,
                "index_options"=>nil,
                "index_type"=>nil,
                "type"=>"partition_key",
                "validator"=>"org.apache.cassandra.db.marshal.UTF8Type"
              },
              {
                "keyspace_name"=>"system",
                "columnfamily_name"=>"schema_triggers",
                "column_name"=>"trigger_name",
                "component_index"=>1,
                "index_name"=>nil,
                "index_options"=>nil,
                "index_type"=>nil,
                "type"=>"clustering_key",
                "validator"=>"org.apache.cassandra.db.marshal.UTF8Type"
              },
              {
                "keyspace_name"=>"system",
                "columnfamily_name"=>"schema_triggers",
                "column_name"=>"trigger_options",
                "component_index"=>2,
                "index_name"=>nil,
                "index_options"=>nil,
                "index_type"=>nil,
                "type"=>"regular",
                "validator"=>
                 "org.apache.cassandra.db.marshal.MapType(org.apache.cassandra.db.marshal.UTF8Type,org.apache.cassandra.db.marshal.UTF8Type)"
              },
              {
                "keyspace_name"=>"system",
                "columnfamily_name"=>"sstable_activity",
                "column_name"=>"columnfamily_name",
                "component_index"=>1,
                "index_name"=>nil,
                "index_options"=>nil,
                "index_type"=>nil,
                "type"=>"partition_key",
                "validator"=>"org.apache.cassandra.db.marshal.UTF8Type"
              },
              {
                "keyspace_name"=>"system",
                "columnfamily_name"=>"sstable_activity",
                "column_name"=>"generation",
                "component_index"=>2,
                "index_name"=>nil,
                "index_options"=>nil,
                "index_type"=>nil,
                "type"=>"partition_key",
                "validator"=>"org.apache.cassandra.db.marshal.Int32Type"
              },
              {
                "keyspace_name"=>"system",
                "columnfamily_name"=>"sstable_activity",
                "column_name"=>"keyspace_name",
                "component_index"=>0,
                "index_name"=>nil,
                "index_options"=>nil,
                "index_type"=>nil,
                "type"=>"partition_key",
                "validator"=>"org.apache.cassandra.db.marshal.UTF8Type"
              },
              {
                "keyspace_name"=>"system",
                "columnfamily_name"=>"sstable_activity",
                "column_name"=>"rate_120m",
                "component_index"=>0,
                "index_name"=>nil,
                "index_options"=>nil,
                "index_type"=>nil,
                "type"=>"regular",
                "validator"=>"org.apache.cassandra.db.marshal.DoubleType"
              },
              {
                "keyspace_name"=>"system",
                "columnfamily_name"=>"sstable_activity",
                "column_name"=>"rate_15m",
                "component_index"=>0,
                "index_name"=>nil,
                "index_options"=>nil,
                "index_type"=>nil,
                "type"=>"regular",
                "validator"=>"org.apache.cassandra.db.marshal.DoubleType"
              },
              {
                "keyspace_name"=>"system_traces",
                "columnfamily_name"=>"events",
                "column_name"=>"activity",
                "component_index"=>1,
                "index_name"=>nil,
                "index_options"=>nil,
                "index_type"=>nil,
                "type"=>"regular",
                "validator"=>"org.apache.cassandra.db.marshal.UTF8Type"
              },
              {
                "keyspace_name"=>"system_traces",
                "columnfamily_name"=>"events",
                "column_name"=>"event_id",
                "component_index"=>0,
                "index_name"=>nil,
                "index_options"=>nil,
                "index_type"=>nil,
                "type"=>"clustering_key",
                "validator"=>"org.apache.cassandra.db.marshal.TimeUUIDType"
              },
              {
                "keyspace_name"=>"system_traces",
                "columnfamily_name"=>"events",
                "column_name"=>"session_id",
                "component_index"=>nil,
                "index_name"=>nil,
                "index_options"=>nil,
                "index_type"=>nil,
                "type"=>"partition_key",
                "validator"=>"org.apache.cassandra.db.marshal.UUIDType"
              },
              {
                "keyspace_name"=>"system_traces",
                "columnfamily_name"=>"events",
                "column_name"=>"source",
                "component_index"=>1,
                "index_name"=>nil,
                "index_options"=>nil,
                "index_type"=>nil,
                "type"=>"regular",
                "validator"=>"org.apache.cassandra.db.marshal.InetAddressType"
              },
              {
                "keyspace_name"=>"system_traces",
                "columnfamily_name"=>"events",
                "column_name"=>"source_elapsed",
                "component_index"=>1,
                "index_name"=>nil,
                "index_options"=>nil,
                "index_type"=>nil,
                "type"=>"regular",
                "validator"=>"org.apache.cassandra.db.marshal.Int32Type"
              },
              {
                "keyspace_name"=>"system_traces",
                "columnfamily_name"=>"events",
                "column_name"=>"thread",
                "component_index"=>1,
                "index_name"=>nil,
                "index_options"=>nil,
                "index_type"=>nil,
                "type"=>"regular",
                "validator"=>"org.apache.cassandra.db.marshal.UTF8Type"
              },
              {
                "keyspace_name"=>"system_traces",
                "columnfamily_name"=>"sessions",
                "column_name"=>"coordinator",
                "component_index"=>0,
                "index_name"=>nil,
                "index_options"=>nil,
                "index_type"=>nil,
                "type"=>"regular",
                "validator"=>"org.apache.cassandra.db.marshal.InetAddressType"
              },
              {
                "keyspace_name"=>"system_traces",
                "columnfamily_name"=>"sessions",
                "column_name"=>"duration",
                "component_index"=>0,
                "index_name"=>nil,
                "index_options"=>nil,
                "index_type"=>nil,
                "type"=>"regular",
                "validator"=>"org.apache.cassandra.db.marshal.Int32Type"
              },
              {
                "keyspace_name"=>"system_traces",
                "columnfamily_name"=>"sessions",
                "column_name"=>"parameters",
                "component_index"=>0,
                "index_name"=>nil,
                "index_options"=>nil,
                "index_type"=>nil,
                "type"=>"regular",
                "validator"=>
                 "org.apache.cassandra.db.marshal.MapType(org.apache.cassandra.db.marshal.UTF8Type,org.apache.cassandra.db.marshal.UTF8Type)"
              },
              {
                "keyspace_name"=>"system_traces",
                "columnfamily_name"=>"sessions",
                "column_name"=>"request",
                "component_index"=>0,
                "index_name"=>nil,
                "index_options"=>nil,
                "index_type"=>nil,
                "type"=>"regular",
                "validator"=>"org.apache.cassandra.db.marshal.UTF8Type"
              },
              {
                "keyspace_name"=>"system_traces",
                "columnfamily_name"=>"sessions",
                "column_name"=>"session_id",
                "component_index"=>nil,
                "index_name"=>nil,
                "index_options"=>nil,
                "index_type"=>nil,
                "type"=>"partition_key",
                "validator"=>"org.apache.cassandra.db.marshal.UUIDType"
              },
              {
                "keyspace_name"=>"system_traces",
                "columnfamily_name"=>"sessions",
                "column_name"=>"started_at",
                "component_index"=>0,
                "index_name"=>nil,
                "index_options"=>nil,
                "index_type"=>nil,
                "type"=>"regular",
                "validator"=>"org.apache.cassandra.db.marshal.TimestampType"
              },
              {
                "keyspace_name"=>"simplex",
                "columnfamily_name"=>"songs",
                "column_name"=>"album",
                "component_index"=>0,
                "index_name"=>nil,
                "index_options"=>nil,
                "index_type"=>nil,
                "type"=>"regular",
                "validator"=>"org.apache.cassandra.db.marshal.UTF8Type"
              },
              {
                "keyspace_name"=>"simplex",
                "columnfamily_name"=>"songs",
                "column_name"=>"artist",
                "component_index"=>0,
                "index_name"=>nil,
                "index_options"=>nil,
                "index_type"=>nil,
                "type"=>"regular",
                "validator"=>"org.apache.cassandra.db.marshal.UTF8Type"
              },
              {
                "keyspace_name"=>"simplex",
                "columnfamily_name"=>"songs",
                "column_name"=>"data",
                "component_index"=>0,
                "index_name"=>nil,
                "index_options"=>nil,
                "index_type"=>nil,
                "type"=>"regular",
                "validator"=>"org.apache.cassandra.db.marshal.BytesType"
              },
              {
                "keyspace_name"=>"simplex",
                "columnfamily_name"=>"songs",
                "column_name"=>"id",
                "component_index"=>nil,
                "index_name"=>nil,
                "index_options"=>nil,
                "index_type"=>nil,
                "type"=>"partition_key",
                "validator"=>"org.apache.cassandra.db.marshal.UUIDType"
              },
              {
                "keyspace_name"=>"simplex",
                "columnfamily_name"=>"songs",
                "column_name"=>"tags",
                "component_index"=>0,
                "index_name"=>nil,
                "index_options"=>nil,
                "index_type"=>nil,
                "type"=>"regular",
                "validator"=>
                 "org.apache.cassandra.db.marshal.SetType(org.apache.cassandra.db.marshal.UTF8Type)"
              },
              {
                "keyspace_name"=>"simplex",
                "columnfamily_name"=>"songs",
                "column_name"=>"title",
                "component_index"=>0,
                "index_name"=>nil,
                "index_options"=>nil,
                "index_type"=>nil,
                "type"=>"regular",
                "validator"=>"org.apache.cassandra.db.marshal.UTF8Type"
              }
            ]
          }
          let(:types) {
            [
              {
                'keyspace_name' => 'simplex',
                'type_name' => 'address',
                'field_names' => [
                  'street',
                  'city',
                  'zip_code',
                  'phones'
                ],
                'field_types' => [
                  'org.apache.cassandra.db.marshal.UTF8Type',
                  'org.apache.cassandra.db.marshal.UTF8Type',
                  'org.apache.cassandra.db.marshal.Int32Type',
                  'org.apache.cassandra.db.marshal.SetType(org.apache.cassandra.db.marshal.UTF8Type)'
                ]
              }
            ]
          }

          before do
            subject.update_keyspaces(host, keyspaces, tables, columns, types)
          end

          it 'correctly parses schema types' do
            table = subject.keyspace('simplex').table('songs')
            expect(table.column('tags').type).to eq([:set, :varchar])
            expect(table.to_cql).to eq(<<-CQL.chomp!)
CREATE TABLE simplex.songs (
  id uuid,
  album varchar,
  artist varchar,
  data blob,
  tags set<varchar>,
  title varchar,
  PRIMARY KEY (id)
)
WITH bloom_filter_fp_chance = 0.01
 AND caching = 'KEYS_ONLY'
 AND comment = ''
 AND compaction = {'class' : 'org.apache.cassandra.db.compaction.SizeTieredCompactionStrategy'}
 AND compression = {'sstable_compression' : 'org.apache.cassandra.io.compress.LZ4Compressor'}
 AND dclocal_read_repair_chance = 0.1
 AND default_time_to_live = 0
 AND gc_grace_seconds = 864000
 AND index_interval = 128
 AND populate_io_cache_on_flush = 'false'
 AND read_repair_chance = 0.0
 AND replicate_on_write = 'true'
 AND speculative_retry = '99.0PERCENTILE';
            CQL
          end
        end
      end
    end
  end
end
